/**
 * GENERATED by `scripts/gen-persistence-catalog.ts` — do not edit by hand; run
 * `pnpm run gen-persistence-catalog` to regenerate (verified fresh by
 * `pnpm run verify-persistence-catalog`, part of `doc-sync`).
 * @module @deepseek-ai/dsh-session/known-event-types
 */

/**
 * Every `SessionEventMap` member declared in this repository — the event
 * vocabulary this build understands. The persistence read path refuses to
 * interpret a log containing a type outside this set unless the event
 * carries the envelope's `ignorable` marker (see `SessionEvent.ignorable`
 * in `./types.ts`): such a log was likely written by a newer harness, and
 * silently skipping a required event would reconstruct a wrong session.
 * Downstream (out-of-repo) plugin events are outside this list by
 * construction. The persisted `SessionEvent.ignorable` marker is the
 * compatibility mechanism; event-name registration was rejected because
 * it does not classify omission safety and would make reads
 * composition-dependent. The rationale is in
 * `.agents/notes/implemented/architecture/2026-08-30-retain-ignorable-external-session-events.md`.
 */
const knownSessionEventTypeValues = Object.freeze([
  'agent-preset/selected',
  'agent/inbox/spliced',
  'approval/asked',
  'approval/decided',
  'approval/policy',
  'assistant/attempt',
  'assistant/message',
  'command/done',
  'command/run',
  'compaction/end',
  'compaction/prune',
  'compaction/start',
  'compaction/summary',
  'feedback/message-delete',
  'feedback/message-put',
  'feedback/record',
  'goal/change',
  'hook/invoked',
  'hook/result',
  'llm/retry',
  'llm/retry-started',
  'model/selection',
  'permission/preset',
  'plan/mode',
  'request/context',
  'request/header',
  'sandbox/mode',
  'schedule/change',
  'session-log-deepseek/delivery-accepted',
  'session/end-seed',
  'session/title',
  'session/title-llm-request',
  'step/end',
  'step/start',
  'subagent/descriptor',
  'subagent/model-selection-policy',
  'system/message',
  'team/member',
  'team/message/delivered',
  'team/message/queued',
  'team/task',
  'todo/write',
  'tool-workflow/agent-end',
  'tool-workflow/agent-start',
  'tool-workflow/run-end',
  'tool-workflow/run-start',
  'tool/call',
  'tool/ptc-dispatch',
  'tool/ptc-dispatch-start',
  'tool/result',
  'turn/end',
  'turn/start',
  'user/message',
  'web/deepseek-search-llm-request',
] as const)

/** One event type understood by this Harness build. */
export type KnownSessionEventType =
  | 'agent-preset/selected'
  | 'agent/inbox/spliced'
  | 'approval/asked'
  | 'approval/decided'
  | 'approval/policy'
  | 'assistant/attempt'
  | 'assistant/message'
  | 'command/done'
  | 'command/run'
  | 'compaction/end'
  | 'compaction/prune'
  | 'compaction/start'
  | 'compaction/summary'
  | 'feedback/message-delete'
  | 'feedback/message-put'
  | 'feedback/record'
  | 'goal/change'
  | 'hook/invoked'
  | 'hook/result'
  | 'llm/retry'
  | 'llm/retry-started'
  | 'model/selection'
  | 'permission/preset'
  | 'plan/mode'
  | 'request/context'
  | 'request/header'
  | 'sandbox/mode'
  | 'schedule/change'
  | 'session-log-deepseek/delivery-accepted'
  | 'session/end-seed'
  | 'session/title'
  | 'session/title-llm-request'
  | 'step/end'
  | 'step/start'
  | 'subagent/descriptor'
  | 'subagent/model-selection-policy'
  | 'system/message'
  | 'team/member'
  | 'team/message/delivered'
  | 'team/message/queued'
  | 'team/task'
  | 'todo/write'
  | 'tool-workflow/agent-end'
  | 'tool-workflow/agent-start'
  | 'tool-workflow/run-end'
  | 'tool-workflow/run-start'
  | 'tool/call'
  | 'tool/ptc-dispatch'
  | 'tool/ptc-dispatch-start'
  | 'tool/result'
  | 'turn/end'
  | 'turn/start'
  | 'user/message'
  | 'web/deepseek-search-llm-request'

const knownSessionEventTypeSet: ReadonlySet<KnownSessionEventType> = new Set(knownSessionEventTypeValues)
const knownSessionEventTypes: ReadonlySet<KnownSessionEventType> = {
  get size() { return knownSessionEventTypeSet.size },
  has(value) { return knownSessionEventTypeSet.has(value) },
  entries() { return knownSessionEventTypeSet.entries() },
  keys() { return knownSessionEventTypeSet.keys() },
  values() { return knownSessionEventTypeSet.values() },
  [Symbol.iterator]() { return knownSessionEventTypeSet[Symbol.iterator]() },
  forEach(callback, thisArg) {
    for (const value of knownSessionEventTypeSet) callback.call(thisArg, value, value, knownSessionEventTypes)
  },
}

/** Immutable view of every event type understood by this Harness build. */
export const KNOWN_SESSION_EVENT_TYPES: ReadonlySet<string> = Object.freeze(knownSessionEventTypes)

/** Whether this Harness build understands one event type.
 * @param type - event type to classify.
 * @returns true when the type belongs to the generated in-repository vocabulary.
 */
export function isKnownSessionEventType(type: string): boolean {
  return knownSessionEventTypeSet.has(type as KnownSessionEventType)
}
